services:
  - type: web
    name: skysegment
    runtime: node
    buildCommand: npm install --no-audit && npm run build
    startCommand: npm start
    envVars:
      - key: ROBOFLOW_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
